export { default as Button } from './Button'
export { default as Img } from './Img'
export { default as Input } from './Input'
export { default as Links } from './Links'
export { default as Title } from './Title'
export { default as Text } from './Text'
